file(GLOB ICON_FILES "${ASSET_DIR}/icons/*.svg")
file(GLOB FONT_FILES "${ASSET_DIR}/fonts/*.otf" "${ASSET_DIR}/fonts/*.ttf")

set(GENERATED "// Generated by GenerateEmbeddedAssets.cmake - do not edit.\n")
string(APPEND GENERATED "#include \"rf/ui/EmbeddedAssets.h\"\n\n")
string(APPEND GENERATED "namespace rf::assets {\nnamespace {\n\n")

set(TABLE "")
set(INDEX 0)

foreach(FILE IN LISTS ICON_FILES FONT_FILES)
    get_filename_component(NAME "${FILE}" NAME)
    get_filename_component(PARENT "${FILE}" DIRECTORY)
    get_filename_component(FOLDER "${PARENT}" NAME)

    file(READ "${FILE}" CONTENT HEX)
    string(LENGTH "${CONTENT}" HEX_LENGTH)
    math(EXPR BYTE_COUNT "${HEX_LENGTH} / 2")

    # "0a1b2c" -> "0x0a,0x1b,0x2c,"
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BYTES "${CONTENT}")

    string(APPEND GENERATED "const unsigned char kBlob${INDEX}[] = {${BYTES}};\n")
    string(APPEND TABLE "    {\"${FOLDER}/${NAME}\", kBlob${INDEX}, ${BYTE_COUNT}},\n")
    math(EXPR INDEX "${INDEX} + 1")
endforeach()

string(APPEND GENERATED "\nstruct Entry {\n")
string(APPEND GENERATED "    const char* name;\n")
string(APPEND GENERATED "    const unsigned char* data;\n")
string(APPEND GENERATED "    std::size_t size;\n};\n\n")
string(APPEND GENERATED "constexpr Entry kEntries[] = {\n${TABLE}};\n\n")
string(APPEND GENERATED "}  // namespace\n\n")

string(APPEND GENERATED "Blob Find(std::string_view name) {\n")
string(APPEND GENERATED "    for (const Entry& e : kEntries)\n")
string(APPEND GENERATED "        if (name == e.name) return Blob{e.data, e.size};\n")
string(APPEND GENERATED "    return Blob{};\n}\n\n")

string(APPEND GENERATED "std::vector<std::string> List(std::string_view folder) {\n")
string(APPEND GENERATED "    std::vector<std::string> out;\n")
string(APPEND GENERATED "    for (const Entry& e : kEntries) {\n")
string(APPEND GENERATED "        std::string_view name(e.name);\n")
string(APPEND GENERATED "        if (name.substr(0, folder.size()) == folder)\n")
string(APPEND GENERATED "            out.emplace_back(name);\n")
string(APPEND GENERATED "    }\n    return out;\n}\n\n")
string(APPEND GENERATED "}  // namespace rf::assets\n")

file(WRITE "${OUTPUT}" "${GENERATED}")
message(STATUS "Embedded ${INDEX} asset(s) into ${OUTPUT}")
